version: '3.2'
services:
  cassandra:
    deploy:
      replicas: 1
    entrypoint:
      - "sh"
      - "-c"
      - export CASSANDRA_SEEDS=$$(nrOfTasks=`getent hosts tasks.cassandra | wc -l` ;
        many=`getent hosts tasks.cassandra | awk '{print $$1}' | sed "/$$(hostname --ip-address)/d"
        | paste -d, -s -` ; printf '%s' $$( [ $${nrOfTasks} -gt 1 ] && echo $${many} ||
        echo "$$(hostname --ip-address)" )) ; /docker-entrypoint.sh cassandra -f
    image: cassandra
    networks:
      - cassnet

networks:
  cassnet:
    driver: overlay
    attachable: true

# Cassandra does not deal well with multiple nodes joining at once
# the idea here is to launch 1 node at a time, up-scaling the service